[package]
name = "music-dl"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
directories = "6.0"
mp4ameta = "0.13"
percent-encoding = "2.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
small-http = { version = "0.2.1", features = ["json"] }
threadpool = "1.8"
