[package]
name = "game2048"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[package.metadata.bundle]
name = "2048"
identifier = "nl.bplaat.2048"
copyright = "Copyright © 2014 Gabriele Cirulli\nCopyright © 2025 Bastiaan van der Plaat"
icon = "meta/macos/icon.icon"

[dependencies]
bwebview = { path = "../../lib/bwebview", features = ["rust-embed"] }
rust-embed = "8.7"

[build-dependencies]
winresource = "0.1.29"
