[package]
name = "XStreaks"
id = "nl.plaatsoft.XStreaks"
version = "0.1.0"

[dependencies]
cocoa = { framework = "Cocoa" }

[package.metadata.bundle]
lipo = true
iconset = "icons/app_icon.iconset"
# FIXME: Currently can't build .icon files in GitHub Actions CI with XCode 26.2
# icon = "icons/icon.icon"
copyright = "Copyright Â© 2025 Bastiaan van der Plaat"
