[package]
name = "navidrome"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[package.metadata.bundle]
name = "Navidrome"
identifier = "nl.bplaat.Navidrome"
copyright = "Copyright Â© 2025 Bastiaan van der Plaat"
icon = "meta/macos/icon.icon"

[lints]
workspace = true

[dependencies]
bwebview = { path = "../../lib/bwebview" }

[build-dependencies]
winresource = "0.1.29"
