[package]
name = "sequelexplorer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[package.metadata.bundle]
name = "Sequel Explorer"
identifier = "nl.bplaat.SequelExplorer"
copyright = "Copyright Â© 2026 Bastiaan van der Plaat"

[lints]
workspace = true

[dependencies]
bsqlite = { path = "../../lib/bsqlite", features = ["bundled"] }
bwebview = { path = "../../lib/bwebview", features = ["rust-embed"] }
rust-embed = "8.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
small-http = { version = "0.2.1", default-features = false, features = [
    "json",
] }
small-router = { version = "0.2.1" }
uuid = { version = "1.0" }
url = { version = "2.0" }
