[package]
name = "sequelexplorer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[package.metadata.bundle]
name = "Sequel Explorer"
identifier = "nl.bplaat.SequelExplorer"
copyright = "Copyright Â© 2026 Bastiaan van der Plaat"
icon = "meta/macos/icon.icon"

[lints]
workspace = true

[dependencies]
base64 = "0.22"
bsqlite = "0.1.2"
bwebview = { path = "../../lib/bwebview", features = [
    "rust-embed",
    "file_dialog",
] }
rust-embed = "8.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7.1"
small-http = { version = "0.2.1", default-features = false, features = [
    "json",
] }
small-router = { version = "0.2.1" }
url = { version = "2.0" }

[target.'cfg(not(target_os = "macos"))'.dependencies]
bsqlite = { version = "0.1.2", features = ["bundled"] }

[build-dependencies]
winresource = "0.1.29"
